#! /bin/bash

# Background folder
cp ./Background/00.png ./Background/01.png
cp ./Background/00.png ./Background/02.png
cp ./Background/00.png ./Background/03.png
cp ./Background/00.png ./Background/04.png
cp ./Background/00.png ./Background/05.png
cp ./Background/00.png ./Background/06.png
cp ./Background/00.png ./Background/07.png
cp ./Background/00.png ./Background/08.png
cp ./Background/00.png ./Background/09.png
cp ./Background/00.png ./Background/10.png
cp ./Background/00.png ./Background/11.png
cp ./Background/00.png ./Background/12.png
cp ./Background/00.png ./Background/13.png
cp ./Background/00.png ./Background/14.png
cp ./Background/00.png ./Background/15.png
cp ./Background/00.png ./Background/16.png
cp ./Background/00.png ./Background/17.png
cp ./Background/00.png ./Background/18.png
cp ./Background/00.png ./Background/19.png
cp ./Background/00.png ./Background/20.png
cp ./Background/00.png ./Background/21.png
cp ./Background/00.png ./Background/22.png
cp ./Background/00.png ./Background/23.png
cp ./Background/00.png ./Background/24.png
cp ./Background/00.png ./Background/25.png
cp ./Background/00.png ./Background/26.png
cp ./Background/00.png ./Background/27.png
cp ./Background/00.png ./Background/28.png
cp ./Background/00.png ./Background/29.png
cp ./Background/00.png ./Background/30.png
cp ./Background/00.png ./Background/31.png
cp ./Background/00.png ./Background/32.png
cp ./Background/00.png ./Background/33.png
cp ./Background/00.png ./Background/Reference.png

# Characters folder
cp ./Chars/00.png ./Chars/01.png
cp ./Chars/00.png ./Chars/02.png
cp ./Chars/00.png ./Chars/03.png
cp ./Chars/00.png ./Chars/04.png
cp ./Chars/00.png ./Chars/05.png
cp ./Chars/00.png ./Chars/06.png
cp ./Chars/00.png ./Chars/07.png
cp ./Chars/00.png ./Chars/08.png
cp ./Chars/00.png ./Chars/09.png
cp ./Chars/00.png ./Chars/10.png
cp ./Chars/00.png ./Chars/11.png
cp ./Chars/00.png ./Chars/12.png
cp ./Chars/00.png ./Chars/13.png
cp ./Chars/00.png ./Chars/Initial.png
