0:	# Gameplay menu
  Height: 8
  Width: 13
  X Offset: 1
  Y Offset: 1
1:	# Dialogue box
  Height: 8
  Width: 30
  X Offset: 1
  Y Offset: 19
2:	# Inventory window
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
3:	# Use/Give/Drop/Help item menu
  Height: 10
  Width: 6
  X Offset: 1
  Y Offset: 1
4:	# PSI Description window
  Height: 6
  Width: 11
  X Offset: 1
  Y Offset: 3
5:	# Telephone contacts and Teleport destinations menu
  Height: 16
  Width: 11
  X Offset: 20
  Y Offset: 1
6:	# Equip menu
  Height: 10
  Width: 20
  X Offset: 8
  Y Offset: 1
7:	# List of equippable items
  Height: 12	# 16
  Width: 13
  X Offset: 18
  Y Offset: 1
8:	# Status window
  Height: 18
  Width: 30
  X Offset: 1
  Y Offset: 1
9:	# Shop windows
  Height: 18
  Width: 19
  X Offset: 12
  Y Offset: 1
10:	# Cash on hand window
  Height: 4
  Width: 8
  X Offset: 1
  Y Offset: 10
11:	# ??? (Unknown, unused?)
  Height: 4
  Width: 11
  X Offset: 1
  Y Offset: 15
12:	# Store window / Debug menu status effects menu
  Height: 16
  Width: 19
  X Offset: 12
  Y Offset: 1
13:	# Escargo Express inventory (Taking items)
  Height: 16
  Width: 24
  X Offset: 7
  Y Offset: 1
14:	# Battle message window
  Height: 6
  Width: 24
  X Offset: 4
  Y Offset: 1
15:	# Standard-width battle menu
  Height: 6
  Width: 21
  X Offset: 1
  Y Offset: 1
16:	# Offense/Defense/Assist PSI selection menu
  Height: 8
  Width: 8
  X Offset: 4
  Y Offset: 1
17:	# PSI Name when selected in battle
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
18:	# Jeff's battle menu
  Height: 6
  Width: 14
  X Offset: 1
  Y Offset: 1
19:	# File selection menu
  Height: 8
  Width: 30
  X Offset: 1
  Y Offset: 2
20:	# Continue/Copy/Delete file menu
  Height: 4
  Width: 22
  X Offset: 5
  Y Offset: 9
21:	# Copy file menu, 2 slots
  Height: 8
  Width: 12
  X Offset: 10
  Y Offset: 16
22:	# Copy file menu, 1 slot
  Height: 6
  Width: 12
  X Offset: 10
  Y Offset: 16
23:	# Delete file confirmation menu
  Height: 10
  Width: 21
  X Offset: 6
  Y Offset: 17
24:	# Text speed selection menu
  Height: 10
  Width: 16
  X Offset: 3
  Y Offset: 14
25:	# Sound mode selection menu
  Height: 8
  Width: 18
  X Offset: 8
  Y Offset: 15
26:	# Character name input
  Height: 4
  Width: 8
  X Offset: 5
  Y Offset: 4
27:	# "Name this X" message
  Height: 4
  Width: 17
  X Offset: 13
  Y Offset: 4
28:	# Letter selection window
  Height: 16
  Width: 30
  X Offset: 1
  Y Offset: 9
29:	# Confirmation box: Ness' name
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 3
30:	# Confirmation box: Paula's name
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 7
31:	# Confirmation box: Jeff's name
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 11
32:	# Confirmation box: Poo's name
  Height: 4
  Width: 7
  X Offset: 7
  Y Offset: 15
33:	# Confirmation box: King's name
  Height: 4
  Width: 8
  X Offset: 20
  Y Offset: 3
34:	# Confirmation box: Favorite food
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 7
35:	# Confirmation box: Favorite thing
  Height: 6
  Width: 13
  X Offset: 15
  Y Offset: 13
36:	# Confirmation box: "Are you sure?"
  Height: 4
  Width: 24
  X Offset: 4
  Y Offset: 21
37:	# Healer / Mach Pizza window (3 choices)
  Height: 8
  Width: 13
  X Offset: 18
  Y Offset: 6
38:	# PSI Name when selecting a single target or single row
  Height: 4
  Width: 12
  X Offset: 12
  Y Offset: 1
39:	# "Register your name, please" window above Player's name input window on Scarabi
  Height: 6
  Width: 26
  X Offset: 3
  Y Offset: 3
40:	# Menu helper window (Who?, Whom?, Where?, etc)
  Height: 4
  Width: 7
  X Offset: 1
  Y Offset: 1
41:	# Character select window with 2 characters  
  Height: 4
  Width: 15
  X Offset: 16
  Y Offset: 8
42:	# Character select window with 3 characters  
  Height: 4
  Width: 21
  X Offset: 10
  Y Offset: 8
43:	# Character select window with 4 characters  
  Height: 4
  Width: 27
  X Offset: 4
  Y Offset: 8
44:	# Give items to other characters window
  Height: 16
  Width: 24
  X Offset: 8
  Y Offset: 2
45:	# Equip menu Offense/Defense listing
  Height: 12	# 6
  Width: 14	# 15
  X Offset: 1	# 3
  Y Offset: 13	# 11
46:	# Offense/Defense/Assist/Other PSI menu
  Height: 10
  Width: 8
  X Offset: 4
  Y Offset: 1
47:	# Save game corrupted, PSI Information windows
  Height: 10
  Width: 30
  X Offset: 1
  Y Offset: 9
48:	# Party leader battle menu
  Height: 6
  Width: 28
  X Offset: 1
  Y Offset: 1
49:	# "To: Enemy" battle window
  Height: 4
  Width: 20
  X Offset: 10
  Y Offset: 4
50:	# Flavor chooser window
  Height: 16
  Width: 15
  X Offset: 14
  Y Offset: 11
51:	# Character select window with 1 character (Debug menu)
  Height: 4
  Width: 9
  X Offset: 22
  Y Offset: 8
52:	# ??? (Unknown, unused)
  Height: 14	# 18
  Width: 16	# 1
  X Offset: 15	# 7
  Y Offset: 13	# 9
